eUseControl.Web1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eUseControl.BusinessLogic;
using eUseControl.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using AutoMapper;
using eUseControl.BusinessLogic.DBModel;
using eUseControl.Domain.Entities.User;

namespace eUseControl.Web1.Controllers
{
     public class AdminController : Controller
     {
          private readonly ISession _session;

          public AdminController()
          {
               var bl = new BussinesLogic();
               _session = bl.GetSessionBL();
          }

          public ActionResult Users(string searchTerm = null, LevelAcces? filterLevel = null)
          {
               var cookie = Request.Cookies["X-KEY"]?.Value;
               var currentUser = _session.GetUserByCookie(cookie);

               if (currentUser == null || currentUser.Level != LevelAcces.Admin)
               {
                    return RedirectToAction("Index", "Home");
               }

               using (var db = new UserContext())
               {
                    var usersQuery = db.Users.AsQueryable();

                    if (!string.IsNullOrEmpty(searchTerm))
                    {
                         usersQuery = usersQuery.Where(u => u.Username.Contains(searchTerm) || u.Email.Contains(searchTerm));
                    }

                    if (filterLevel.HasValue)
                    {
                         usersQuery = usersQuery.Where(u => u.Level == filterLevel.Value);
                    }

                    var users = usersQuery.ToList();

              
                    ViewBag.SearchTerm = searchTerm;
                    ViewBag.FilterLevel = filterLevel;

                    return View(users);
               }
          }

          [HttpPost]
          public ActionResult DeleteUser(int id)
          {
               var cookie = Request.Cookies["X-KEY"]?.Value;
               var currentUser = _session.GetUserByCookie(cookie);

               if (currentUser == null || currentUser.Level != LevelAcces.Admin)
               {
                    return RedirectToAction("Index", "Home");
               }

               using (var db = new UserContext())
               {
                    var user = db.Users.FirstOrDefault(u => u.Id == id);
                    if (user != null)
                    {
                
                         if (user.Id != currentUser.Id)
                         {
                              db.Users.Remove(user);
                              db.SaveChanges();
                         }
                    }
               }

               return RedirectToAction("Users");
          }
          [HttpPost]
          public ActionResult ToggleActive(int id)
          {
               var cookie = Request.Cookies["X-KEY"]?.Value;
               var currentUser = _session.GetUserByCookie(cookie);

               if (currentUser == null || currentUser.Level != LevelAcces.Admin)
               {
                    return RedirectToAction("Index", "Home");
               }

               using (var db = new UserContext())
               {
                    var user = db.Users.FirstOrDefault(u => u.Id == id);
                    if (user != null && user.Id != currentUser.Id) 
                    {
                         user.IsActive = !user.IsActive;
                         db.Entry(user).State = EntityState.Modified;
                         db.SaveChanges();
                    }
               }
               return RedirectToAction("Users");
          }
          [HttpPost]
          public ActionResult ResetPassword(int id)
          {
               var cookie = Request.Cookies["X-KEY"]?.Value;
               var currentUser = _session.GetUserByCookie(cookie);

               if (currentUser == null || currentUser.Level != LevelAcces.Admin)
               {
                    return RedirectToAction("Index", "Home");
               }

               using (var db = new UserContext())
               {
                    var user = db.Users.FirstOrDefault(u => u.Id == id);
                    if (user != null)
                    {
                  
                         string newPassword = "Temp1234";

                    
                         user.PasswordHash = HashPassword(newPassword);

                         db.Entry(user).State = EntityState.Modified;
                         db.SaveChanges();

                   
                    }
               }
               return RedirectToAction("Users");
          }

          private string HashPassword(string newPassword)
          {
               throw new NotImplementedException();
          }
     }
}

eUseControl.Web1/Controllers/AlteServiciiController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;
using eUseControl.Web1.Models; // Assuming you have a Programare model defined here

namespace eUseControl.Web1.Controllers
{
     public class AlteServiciiController : Controller
     {
          private string connectionString = ConfigurationManager.ConnectionStrings["eUseControl"].ConnectionString;

          public ActionResult ProgramariAlteServicii()
          {
               var programari = new List<Programare>();

               using (SqlConnection conn = new SqlConnection(connectionString))
               {
                    string query = "SELECT * FROM Programari WHERE Serviciu = @Serviciu";
                    SqlCommand cmd = new SqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@Serviciu", "Altul");

                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                         var p = new Programare
                         {
                              Id = (int)reader["Id"],
                              Nume = reader["Nume"].ToString(),
                              Prenume = reader["Prenume"].ToString(),
                              Telefon = reader["Telefon"].ToString(),
                              DataProgramare = (DateTime)reader["DataProgramare"],
                              Serviciu = reader["Serviciu"].ToString()
                         };
                         programari.Add(p);
                    }
               }

               return View(programari);
          }
     }
}

eUseControl.Web1/Controllers/ProgramareController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Web.Mvc;
using eUseControl.Domain.Enums;
using eUseControl.Web1.Models;

namespace eUseControl.Web1.Controllers
{
    public class ProgramareController : Controller
    {
        private string connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["eUseControl"].ConnectionString;

        public ActionResult Index()
        {
            if (Session["IsAuthenticated"] != null && (bool)Session["IsAuthenticated"] == true)
            {
                return View();
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Trimite(Programare model)
        {
            if (Session["IsAuthenticated"] == null || (bool)Session["IsAuthenticated"] == false)
            {
                return RedirectToAction("Index", "Login");
            }

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string query = "INSERT INTO Programari (Nume, Prenume, Telefon, DataProgramare, Serviciu, Email) VALUES (@Nume, @Prenume, @Telefon, @DataProgramare, @Serviciu, @Email)";
                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@Nume", model.Nume);
                cmd.Parameters.AddWithValue("@Prenume", model.Prenume);
                cmd.Parameters.AddWithValue("@Telefon", model.Telefon);
                cmd.Parameters.AddWithValue("@DataProgramare", model.DataProgramare);
                cmd.Parameters.AddWithValue("@Serviciu", model.Serviciu);
                cmd.Parameters.AddWithValue("@Email", Session["Email"] ?? "");
                conn.Open();
                cmd.ExecuteNonQuery();
            }

            return RedirectToAction("Confirmare");
        }

        public ActionResult Confirmare()
        {
            return View();
        }

        public ActionResult ProgramarileMele()
        {
            if (Session["IsAuthenticated"] == null || !(bool)Session["IsAuthenticated"])
            {
                return RedirectToAction("Index", "Login");
            }

            var programari = new List<Programare>();

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string query = "SELECT * FROM Programari WHERE Email = @Email ORDER BY DataProgramare DESC";
                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@Email", Session["Email"] ?? "");

                conn.Open();
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    programari.Add(new Programare
                    {
                        Id = (int)reader["Id"],
                        Nume = reader["Nume"].ToString(),
                        Prenume = reader["Prenume"].ToString(),
                        Telefon = reader["Telefon"].ToString(),
                        DataProgramare = (DateTime)reader["DataProgramare"],
                        Serviciu = reader["Serviciu"].ToString(),
                        PacientEmail = reader["Email"].ToString(),
                        Stare = Enum.TryParse(reader["Stare"].ToString(), out StareProgramare stare) ? stare : StareProgramare.InAsteptare
                    });
                }
            }

            return View(programari);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SchimbaStare(int id, int stareNoua, string specialitate)
        {
            if (Session["IsAuthenticated"] == null || !(bool)Session["IsAuthenticated"])
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Enum.IsDefined(typeof(StareProgramare), stareNoua))
            {
                TempData["ErrorMessage"] = "Starea programării nu este validă.";
                return RedirectToAction("ProgramarileMele");
            }

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string query = "UPDATE Programari SET Stare = @StareNoua WHERE Id = @Id";
                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@StareNoua", stareNoua);
                cmd.Parameters.AddWithValue("@Id", id);

                conn.Open();
                cmd.ExecuteNonQuery();
            }

        
            if (!string.IsNullOrEmpty(specialitate))
            {
                return RedirectToAction("Programari" + specialitate, specialitate);
            }

            return RedirectToAction("ProgramarileMele");
        }
    }
}

eUseControl.Web1/Views/Shared/_About.cshtml
    <div class="container">
        <div class="row g-5">
            <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                <div class="d-flex flex-column">
                    <img class="img-fluid rounded w-75 align-self-end" src="~/Content/img/about-1.jpg" alt="">
                    <img class="img-fluid rounded w-50 bg-white pt-3 pe-3" src="~/Content/img/about-2.jpg" alt="" style="margin-top: -25%;">
                </div>
            </div>
            <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                <p class="d-inline-block border rounded-pill py-1 px-4">Despre noi</p>
                <h1 class="mb-4">De ce ne-ai alege? Află acum!</h1>
                <p>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                <p class="mb-4">Stet no et lorem dolor et diam, amet duo ut dolore vero eos. No stet est diam rebum amet diam ipsum. Clita clita labore, dolor duo nonumy clita sit at, sed sit sanctus dolor eos.</p>
                <p><i class="far fa-check-circle text-primary me-3"></i>Servicii medicale de calitate</p>
                <p><i class="far fa-check-circle text-primary me-3"></i>Doar doctori calificați</p>
                <p><i class="far fa-check-circle text-primary me-3"></i>Experți în investigarea medicală</p>
                <a class="btn btn-primary rounded-pill py-3 px-5 mt-3" href="">Citește mai mult</a>
            </div>
        </div>
    </div>

eUseControl.Web1/Views/Shared/_Appointment.cshtml
<div class="container">
    <div class="row g-5">
        <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
            <p class="d-inline-block border rounded-pill py-1 px-4">Programare</p>
            <h1 class="mb-4">Realizează o programare la doctor</h1>
            <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
            <div class="bg-light rounded d-flex align-items-center p-5 mb-4">
                <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-white" style="width: 55px; height: 55px;">
                    <i class="fa fa-phone-alt text-primary"></i>
                </div>
                <div class="ms-4">
                    <p class="mb-2">Sună acum</p>
                    <h5 class="mb-0">+012 345 6789</h5>
                </div>
            </div>
            <div class="bg-light rounded d-flex align-items-center p-5">
                <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-white" style="width: 55px; height: 55px;">
                    <i class="fa fa-envelope-open text-primary"></i>
                </div>
                <div class="ms-4">
                    <p class="mb-2">Scrie un email</p>
                    <h5 class="mb-0">clinica@gmail.com</h5>
                </div>
            </div>
        </div>
        <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
            <div class="bg-light rounded h-100 d-flex align-items-center p-5">
                <form>
                    <div class="row g-3">
                        <div class="col-12 col-sm-6">
                            <input type="text" class="form-control border-0" placeholder="Numele" style="height: 55px;">
                        </div>
                        <div class="col-12 col-sm-6">
                            <input type="email" class="form-control border-0" placeholder="Email-ul" style="height: 55px;">
                        </div>
                        <div class="col-12 col-sm-6">
                            <input type="text" class="form-control border-0" placeholder="Nr. telefon" style="height: 55px;">
                        </div>
                        <div class="col-12 col-sm-6">
                            <select class="form-select border-0" style="height: 55px;">
                                <option selected>Alege doctor</option>
                                <option value="1">Doctor 1</option>
                                <option value="2">Doctor 2</option>
                                <option value="3">Doctor 3</option>
                            </select>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="date" id="date" data-target-input="nearest">
                                <input type="text"
                                       class="form-control border-0 datetimepicker-input"
                                       placeholder="Alege data" data-target="#date" data-toggle="datetimepicker" style="height: 55px;">
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="time" id="time" data-target-input="nearest">
                                <input type="text"
                                       class="form-control border-0 datetimepicker-input"
                                       placeholder="Alege ora" data-target="#time" data-toggle="datetimepicker" style="height: 55px;">
                            </div>
                        </div>
                        <div class="col-12">
                            <textarea class="form-control border-0" rows="5" placeholder="Descrie problema"></textarea>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Programează-te</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eUseControl.Web1/Views/Shared/_Feature.cshtml
<div class="container feature px-lg-0">
    <div class="row g-0 mx-lg-0">
        <div class="col-lg-6 feature-text py-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="p-lg-5 ps-lg-0">
                <p class="d-inline-block border rounded-pill text-light py-1 px-4">Avantaje</p>
                <h1 class="text-white mb-4">De ce să ne alegi</h1>
                <p class="text-white mb-4 pb-2">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo erat amet</p>
                <div class="row g-4">
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-light" style="width: 55px; height: 55px;">
                                <i class="fa fa-user-md text-primary"></i>
                            </div>
                            <div class="ms-4">
                                <p class="text-white mb-2">Experimentați</p>
                                <h5 class="text-white mb-0">Doctori</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-light" style="width: 55px; height: 55px;">
                                <i class="fa fa-check text-primary"></i>
                            </div>
                            <div class="ms-4">
                                <p class="text-white mb-2">De calitate</p>
                                <h5 class="text-white mb-0">Servicii</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-light" style="width: 55px; height: 55px;">
                                <i class="fa fa-comment-medical text-primary"></i>
                            </div>
                            <div class="ms-4">
                                <p class="text-white mb-2">Pozitive</p>
                                <h5 class="text-white mb-0">Consultații</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <div class="d-flex flex-shrink-0 align-items-center justify-content-center rounded-circle bg-light" style="width: 55px; height: 55px;">
                                <i class="fa fa-headphones text-primary"></i>
                            </div>
                            <div class="ms-4">
                                <p class="text-white mb-2">24 Ore</p>
                                <h5 class="text-white mb-0">Suport</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 pe-lg-0 wow fadeIn" data-wow-delay="0.5s" style="min-height: 400px;">
            <div class="position-relative h-100">
                <img class="position-absolute img-fluid w-100 h-100" src="~/Content/img/feature.jpg" style="object-fit: cover;" alt="">
            </div>
        </div>
    </div>
</div>

eUseControl.Web1/Views/Shared/_Footer.cshtml
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Adresa</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Strada Independenței 26, Chișinău, Moldova</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>clinica@gmail.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Servicii</h5>
                <a class="btn btn-link" href="">Cardiologie</a>
                <a class="btn btn-link" href="">Starea Pulmonară</a>
                <a class="btn btn-link" href="">Neurologie</a>
                <a class="btn btn-link" href="">Pediatrie</a>
                <a class="btn btn-link" href="">Laborator</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Link-urile</h5>
                <a class="btn btn-link" href="">Despre noi</a>
                <a class="btn btn-link" href="">Contacte</a>
                <a class="btn btn-link" href="">Servicii</a>
                <a class="btn btn-link" href="">Reguli și condiții</a>
                <a class="btn btn-link" href="">Suport</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Informații extra</h5>
                <p>Luni - Vineri (08:00 - 20:00), Sâmbătă (09:00 - 14:00).</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Email-ul dvs">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>

eUseControl.Web1/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using System.Web.UI.WebControls
@using System.Linq;

@{
    var isAuthenticated = Session["IsAuthenticated"] != null && (bool)Session["IsAuthenticated"];
    var userLevel = Session["Level"] != null ? Convert.ToInt32(Session["Level"]) : -1;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>Clinică</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <title>eUseSystem | @ViewBag.Title </title>
    <!-- Favicon -->
    <link href="~/Content/img/favicon.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&amp;family=Roboto:wght@500;700;900&amp;display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/owlcarouselmin/css")
    @Styles.Render("~/bundles/tempusdominus-bootstrap-4-min/css")

    <!-- Customized Bootstrap Stylesheet -->
    @Styles.Render("~/bundles/bootstrap/css")

    <!-- Template Stylesheet -->
    @Styles.Render("~/bundles/style/css")
</head>
<body>
    <section class="wrapper">
        <!-- Topbar -->
        <div class="container-fluid bg-light p-0 wow fadeIn" data-wow-delay="0.1s">
            @Html.Partial("_Topbar")
        </div>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0 wow fadeIn" data-wow-delay="0.1s">
            @Html.Partial("_Navbar")

            @if (isAuthenticated && userLevel == 0)
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ProgramarileMele", "Programare")">Programările mele</a>
                </li>
            }
        </nav>

        <section class="content">
            @RenderBody()
        </section>

        <!-- Footer -->
        <div class="container-fluid bg-dark text-light footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
            @Html.Partial("_Footer")
        </div>

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

        @Scripts.Render("~/bundles/jquery/js")
        @Scripts.Render("~/bundles/wow/js")
        @Scripts.Render("~/bundles/easing/js")
        @Scripts.Render("~/bundles/waypoints/js")
        @Scripts.Render("~/bundles/counterup/js")
        @Scripts.Render("~/bundles/owl-carousel-min/js")
        @Scripts.Render("~/bundles/tempusdominus/js")

        @Scripts.Render("~/bundles/main/js")

        @RenderSection("scripts", required: false)
    </section>
</body>
</html>

eUseControl.Web1/Views/Shared/_Navbar.cshtml
@using eUseControl.Web1.Extension
@using eUseControl.Domain.Enums
@using eUseControl.Domain.Entities.User
@{
    var user = System.Web.HttpContext.Current.GetMySessionObject();
}
<a href="@Url.Action("Index", "Home")" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
    <h1 class="m-0 text-primary"><i class="far fa-hospital me-3"></i>Clinică</h1>
</a>
<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto p-4 p-lg-0">
        @if (user != null && user.Level == LevelAcces.DoctorCardiologie)
        {
            <a href="@Url.Action("ProgramariCardiologie", "Cardiologie")" class="nav-item nav-link">Programari</a>
        }
        @if (user != null && user.Level == LevelAcces.DoctorDermatologie)
        {
            <a href="@Url.Action("ProgramariDermatologie", "Dermatologie")" class="nav-item nav-link">Programari</a>
        }
        @if (user != null && user.Level == LevelAcces.DoctorORL)
        {
            <a href="@Url.Action("ProgramariORL", "ORL")" class="nav-item nav-link">Programari</a>
        }
        @if (user != null && user.Level == LevelAcces.DoctorAlteServicii)
        {
            <a href="@Url.Action("ProgramariAlteServicii", "AlteServicii")" class="nav-item nav-link">Programari</a>
        }
        @if (user != null && user.Level == LevelAcces.Admin)
        {
            <a href="@Url.Action("Users", "Admin")" class="nav-item nav-link">Utilizatori</a>
        }

        @if (user != null && user.Level == LevelAcces.User)
        {
            <a href="@Url.Action("ProgramarileMele", "Programare")" class="nav-item nav-link">Programările Mele</a>
        }

        <a href="~/Home/Index" class="nav-item nav-link @(ViewData["Title"] == "Index" ? "active" : "")">Acasă</a>
        <a href="~/Home/About" class="nav-item nav-link @(ViewData["Title"] == "About" ? "active" : "")">Despre noi</a>
        <a href="~/Home/Service" class="nav-item nav-link @(ViewData["Title"] == "Service" ? "active" : "")">Servicii</a>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pagini</a>
            <div class="dropdown-menu rounded-0 rounded-bottom m-0">
                <a href="avantaje.html" class="dropdown-item">Avantaje</a>
                <a href="doctori.html" class="dropdown-item">Doctori</a>
                <a href="programare.html" class="dropdown-item">Programare</a>
                <a href="recenzii.html" class="dropdown-item">Recenzii</a>
                <a href="404.html" class="dropdown-item">Pagina 404</a>
            </div>
        </div>
        <a href="~/Home/Contact" class="nav-item nav-link @(ViewData["Title"] == "Contact" ? "active" : "")">Contacte</a>

        @if (user != null)
        {
            <a class="nav-item nav-link">Salut, @user.Username!</a>
            <a href="~/Login/Logout" class="btn btn-outline-light">Logout</a>
        }
        else
        {
            <a href="~/Login/Index" class="btn btn-outline-light">Login</a>
        }
    </div>

    <a href="@Url.Action("Index", "Programare")" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">
        Programare <i class="fa fa-arrow-right ms-3"></i>
    </a>
</div>

eUseControl.Web1/Views/Shared/_Spinner.cshtml
	<div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status">
		<span class="sr-only">Loading...</span>
	</div>