eUseControl.Web1/Controllers/LoginController.cs
using System;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using eUseControl.BusinessLogic;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.User;
using eUseControl.Web1.Models;

namespace eUseControl.Web1.Controllers
{
    public class LoginController : Controller
    {
        private readonly ISession _session;

        public LoginController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBL();
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin login)
        {
            if (ModelState.IsValid)
            {
                var data = Mapper.Map<ULoginData>(login);

                data.LoginIp = Request.UserHostAddress;
                data.LoginDateTime = DateTime.Now;

                var userLogin = _session.UserLogin(data);

                if (userLogin.Status)
                {
                    Session["IsAuthenticated"] = true;

                 
                    Session["Email"] = userLogin.Email;

                
                    Session["Telefon"] = userLogin.Telefon;

                
                    HttpCookie cookie = _session.GenCookie(login.UserName);
                    ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, userLogin.StatusMsg);
                    return View();
                }
            }

            return View();
        }

        public ActionResult Logout()
        {
            if (Request.Cookies["X-KEY"] != null)
            {
                var cookie = new HttpCookie("X-KEY")
                {
                    Expires = DateTime.Now.AddDays(-1)
                };
                Response.Cookies.Add(cookie);
            }

            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

eUseControl.Web1/Controllers/RegisterController.cs
using System;
using System.Web.Mvc;
using AutoMapper;
using eUseControl.BusinessLogic;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.User;
using eUseControl.Web1.Models;

namespace eUseControl.Web1.Controllers
{
     public class RegisterController : Controller
     {
          private readonly ISession _session;

          public RegisterController()
          {
               var bl = new BussinesLogic();
               _session = bl.GetSessionBL();
          }

          public ActionResult Index()
          {
               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Index(UserRegister register)
          {
              
               if (register.Role == "Admin" && register.AdminSecret != "superadmin")
               {
                    ModelState.AddModelError("", "Codul secret pentru admin este invalid.");
                    return View(register);
               }

               if (ModelState.IsValid)
               {
                    var data = Mapper.Map<URegisterData>(register);
                    data.RegisterIp = Request.UserHostAddress;
                    data.RegisterDateTime = DateTime.Now;

                    
                    data.Role = register.Role;

                    var registerResult = _session.UserRegister(data);
                    if (registerResult.Status)
                    {
                         return RedirectToAction("Index", "Login");
                    }
                    else
                    {
                         ModelState.AddModelError("", registerResult.StatusMsg);
                    }
               }

               return View(register);
          }

     }
}

eUseControl.Web1/Views/Login/Index.cshtml
@model eUseControl.Web1.Models.UserLogin
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-center animated slideInDown">
    <div class="view-header">
        <div class="header-icon">
            <i class="pe page-header-icon pe-7s-unlock"></i>
        </div>
        <div class="header-title">
            <h3>Login</h3>
            <small>
                Please enter your credentials to login.
            </small>
        </div>
    </div>

    <div class="panel panel-filled">
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { id = "LoginForm" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(m => m.UserName, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(m => m.UserName, new
                    {
                        placeholder = "example@gmail.com",
                        title = "Please enter your username",
                        @class = "form-control"
                    })
                    <span class="help-block small">Your unique username to app</span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Password, htmlAttributes: new { @class = "control-label" })
                    @Html.PasswordFor(m => m.Password, new
                    {
                        placeholder = "******",
                        title = "Please enter your password",
                        @class = "form-control"
                    })
                    <span class="help-block small">Your strong password</span>
                </div>

                <div>
                    <button type="submit" class="btn btn-accent">Login</button>
                    <a class="btn btn-default" href="@Url.Action("Index", "Register")">Register</a>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.19.5/jquery.validate.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $("#LoginForm").validate({
                rules: {
                    UserName: { required: true },
                    Password: { required: true }
                },
                submitHandler: function (form) {
                    form.submit();
                },
                errorPlacement: function (error, element) {
                    $(element)
                        .closest("form")
                        .find("label[for='" + element.attr("id") + "']")
                        .append(error);
                },
                errorElement: "span"
            });
        });
    </script>
}